[package]
name = "yogi"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[profile.release]
lto = "thin"

[dependencies]
arrayvec = "0.7.1"
thiserror = "1.0.26"
petgraph = "0.6.0"
ahash = "0.7.4"
